/* eslint-disable security/detect-object-injection */
import {ConstrainedObjectModel} from '@asyncapi/modelina';
import {getCliVersion} from '../../../../telemetry/collector';
import {ChannelPayload} from '../../../types';
import {ensureRelativePath, joinPath, relativePath} from '../../../utils';
import {
  ChannelFunctionTypes,
  TypeScriptChannelRenderType,
  TypeScriptChannelRenderedFunctionType,
  receivingFunctionTypes,
  sendingFunctionTypes
} from '../channels/types';
import {TypeScriptClientRenderType} from '../client/types';
import {TypeScriptPayloadRenderType} from '../payloads';
import {TypeScriptTypesRenderType} from '../types';
import {
  TypeScriptReadmeContext,
  TypeScriptReadmeGenerator,
  TypeScriptReadmeGeneratorInternal,
  TypeScriptReadmeRenderType,
  defaultTypeScriptReadmeGenerator,
  zodTypescriptReadmeGenerator
} from './types';

export {
  TypeScriptReadmeContext,
  TypeScriptReadmeGenerator,
  TypeScriptReadmeGeneratorInternal,
  TypeScriptReadmeRenderType,
  defaultTypeScriptReadmeGenerator,
  zodTypescriptReadmeGenerator
};

const README_SEPARATOR = '\n\n---\n\n';
const HTTP_CLIENT_PROTOCOL = 'http_client';
const CODE_FENCE = '```';
const TS_FENCE = '```ts';
// Only used to build `import { X } from '...'` example statements; anything
// that is not a plain identifier (unions, primitives) cannot be imported.
const IDENTIFIER_REGEX = /^[A-Za-z_$][\w$]*$/;

const PROTOCOL_LABELS: Record<string, string> = {
  nats: 'NATS',
  kafka: 'Kafka',
  mqtt: 'MQTT',
  amqp: 'AMQP',
  event_source: 'EventSource',
  websocket: 'WebSocket'
};

interface HttpOperationExample {
  functionName: string;
  hasBody: boolean;
  hasParameters: boolean;
  requestType?: string;
  replyType?: string;
}

export async function generateTypescriptReadme(
  context: TypeScriptReadmeContext
): Promise<TypeScriptReadmeRenderType> {
  const {generator} = context;
  const dependencyOutputs = context.dependencyOutputs ?? {};
  const content = renderReadme({generator, dependencyOutputs});
  return {
    content,
    generator,
    files: [
      {
        path: joinPath(normalizeBasePath(generator.outputPath), 'README.md'),
        content
      }
    ]
  };
}

/**
 * A bare '.' (or '') output directory is the project root; collapse it so joined
 * paths stay clean ('README.md', not './README.md') and relative paths computed
 * against it don't gain a spurious leading '..'.
 */
function normalizeBasePath(outputPath: string): string {
  return outputPath === '.' ? '' : outputPath;
}

function renderReadme({
  generator,
  dependencyOutputs
}: {
  generator: TypeScriptReadmeGeneratorInternal;
  dependencyOutputs: Record<string, any>;
}): string {
  const generatedContent = renderGeneratedContent({
    generator,
    dependencyOutputs
  });
  const introduction = generator.introduction;
  if (introduction && introduction.trim() !== '') {
    return `${introduction.trimEnd()}${README_SEPARATOR}${generatedContent}`;
  }
  return generatedContent;
}

function renderGeneratedContent({
  generator,
  dependencyOutputs
}: {
  generator: TypeScriptReadmeGeneratorInternal;
  dependencyOutputs: Record<string, any>;
}): string {
  const lines: string[] = [`# ${generator.packageName ?? 'Generated Code'}`];
  if (generator.packageVersion) {
    lines.push('', `Version ${generator.packageVersion}`);
  }
  if (generator.packageName) {
    lines.push('', ...renderInstallSection(generator.packageName));
  }
  const usageLines = renderUsageSections({generator, dependencyOutputs});
  if (usageLines.length > 0) {
    lines.push('', '## Usage', '', ...usageLines);
  }
  const suffix =
    generator.suffix ??
    `> Generated by \`@the-codegen-project/cli\` v${getCliVersion()}.`;
  lines.push('', suffix, '');
  return lines.join('\n');
}

function renderInstallSection(packageName: string): string[] {
  return [
    '## Install',
    '',
    '```bash',
    `npm install ${packageName}`,
    CODE_FENCE,
    '',
    '```bash',
    `yarn add ${packageName}`,
    CODE_FENCE,
    '',
    '```bash',
    `pnpm add ${packageName}`,
    CODE_FENCE
  ];
}

function renderUsageSections({
  generator,
  dependencyOutputs
}: {
  generator: TypeScriptReadmeGeneratorInternal;
  dependencyOutputs: Record<string, any>;
}): string[] {
  const channels = resolveDependencyOutput<TypeScriptChannelRenderType>({
    dependencyOutputs,
    generatorId: generator.channelsGeneratorId,
    markerProperty: 'renderedFunctions'
  });
  const payloads = resolveDependencyOutput<TypeScriptPayloadRenderType>({
    dependencyOutputs,
    generatorId: generator.payloadsGeneratorId,
    markerProperty: 'otherModels'
  });
  const types = resolveTypesOutput({
    dependencyOutputs,
    generatorId: generator.typesGeneratorId
  });
  const client = resolveDependencyOutput<TypeScriptClientRenderType>({
    dependencyOutputs,
    generatorId: generator.clientGeneratorId,
    markerProperty: 'protocolResult'
  });

  const blocks: string[][] = [];
  if (channels) {
    blocks.push(...renderChannelBlocks({generator, channels}));
  }
  if (client) {
    blocks.push(
      renderClientSection({
        client,
        channels,
        importPath: resolveExampleImportPath({
          generator,
          targetOutputPath: client.files[0]
            ? client.files[0].path.replace(/\.ts$/, '')
            : generator.outputPath
        })
      })
    );
  }
  if (payloads) {
    blocks.push(
      renderPayloadsSection({
        payloads,
        importPath: resolveExampleImportPath({
          generator,
          targetOutputPath: payloads.generator.outputPath
        })
      })
    );
  }
  if (types) {
    blocks.push(
      renderTypesSection({
        types,
        importPath: resolveExampleImportPath({
          generator,
          targetOutputPath: types.generator.outputPath
        })
      })
    );
  }

  const lines: string[] = [];
  for (const block of blocks) {
    if (block.length === 0) {
      continue;
    }
    if (lines.length > 0) {
      lines.push('');
    }
    lines.push(...block);
  }
  return lines;
}

function renderChannelBlocks({
  generator,
  channels
}: {
  generator: TypeScriptReadmeGeneratorInternal;
  channels: TypeScriptChannelRenderType;
}): string[][] {
  const blocks: string[][] = [];
  const httpOperations = extractHttpOperations(channels);
  if (httpOperations.length > 0) {
    blocks.push(
      renderHttpUsageSection({
        importPath: resolveExampleImportPath({
          generator,
          targetOutputPath: channels.generator.outputPath,
          subPath: HTTP_CLIENT_PROTOCOL
        }),
        operations: httpOperations
      })
    );
  }
  for (const [protocol, functions] of Object.entries(
    channels.renderedFunctions
  )) {
    if (protocol !== HTTP_CLIENT_PROTOCOL && functions.length > 0) {
      blocks.push(
        renderMessagingProtocolSection({
          protocol,
          functions,
          importPath: resolveExampleImportPath({
            generator,
            targetOutputPath: channels.generator.outputPath,
            subPath: protocol
          })
        })
      );
    }
  }
  return blocks;
}

function resolveDependencyOutput<T>({
  dependencyOutputs,
  generatorId,
  markerProperty
}: {
  dependencyOutputs: Record<string, any>;
  generatorId: string;
  markerProperty: string;
}): T | undefined {
  const candidate = dependencyOutputs[generatorId];
  if (
    candidate &&
    typeof candidate === 'object' &&
    markerProperty in candidate
  ) {
    return candidate as T;
  }
  return undefined;
}

function resolveTypesOutput({
  dependencyOutputs,
  generatorId
}: {
  dependencyOutputs: Record<string, any>;
  generatorId: string;
}): TypeScriptTypesRenderType | undefined {
  const candidate = resolveDependencyOutput<TypeScriptTypesRenderType>({
    dependencyOutputs,
    generatorId,
    markerProperty: 'result'
  });
  // The channels render output also exposes `result`; only accept outputs
  // that cannot be mistaken for another generator's.
  if (candidate && !('renderedFunctions' in candidate)) {
    return candidate;
  }
  return undefined;
}

function resolveExampleImportPath({
  generator,
  targetOutputPath,
  subPath
}: {
  generator: TypeScriptReadmeGeneratorInternal;
  targetOutputPath: string;
  subPath?: string;
}): string {
  if (generator.packageName) {
    return generator.packageName;
  }
  const target = subPath
    ? joinPath(targetOutputPath, subPath)
    : targetOutputPath;
  const relative = relativePath(
    normalizeBasePath(generator.outputPath),
    target
  );
  return `./${ensureRelativePath(relative)}`;
}

function extractHttpOperations(
  channels: TypeScriptChannelRenderType
): HttpOperationExample[] {
  const httpFunctions = channels.renderedFunctions[HTTP_CLIENT_PROTOCOL] ?? [];
  const operations: HttpOperationExample[] = [];
  for (const httpFunction of httpFunctions) {
    if (
      httpFunction.functionType === ChannelFunctionTypes.HTTP_CLIENT &&
      httpFunction.functionName
    ) {
      operations.push({
        functionName: httpFunction.functionName,
        hasBody: Boolean(httpFunction.messageType),
        hasParameters: Boolean(httpFunction.parameterType),
        requestType: httpFunction.messageType || undefined,
        replyType: httpFunction.replyType
      });
    }
  }
  return operations;
}

function pickPrimaryHttpOperation(
  operations: HttpOperationExample[]
): HttpOperationExample {
  const simple = operations.find(
    (operation) => !operation.hasBody && !operation.hasParameters
  );
  return simple ?? operations[0];
}

function renderHttpUsageSection({
  importPath,
  operations
}: {
  importPath: string;
  operations: HttpOperationExample[];
}): string[] {
  const primary = pickPrimaryHttpOperation(operations);
  const replyTypeComment = primary.replyType
    ? `   // typed as ${primary.replyType}`
    : '   // typed response body';

  const contextLines = [`  server: 'https://api.example.com',`];
  if (primary.hasParameters) {
    contextLines.push('  parameters, // path parameters for this operation');
  }
  if (primary.hasBody) {
    const requestTypeSuffix = primary.requestType
      ? ` (${primary.requestType})`
      : '';
    contextLines.push(`  payload, // request body${requestTypeSuffix}`);
  }
  contextLines.push(
    `  auth: { type: 'bearer', token: process.env.API_TOKEN ?? '' },`
  );

  const lines = [
    '### HTTP operations',
    '',
    'Each API operation is exported as a standalone, fully typed function. Call one with a',
    'context object and it returns the deserialized response alongside HTTP metadata.',
    '',
    TS_FENCE,
    `import { ${primary.functionName} } from '${importPath}'`,
    '',
    `const response = await ${primary.functionName}({`,
    ...contextLines,
    '})',
    '',
    'console.log(response.status) // HTTP status code',
    `console.log(response.data)${replyTypeComment}`,
    CODE_FENCE,
    '',
    'Every operation accepts a context extending `HttpClientContext`:',
    '',
    '- `server` — base URL of the API.',
    '- `auth` — `bearer`, `basic`, `apiKey`, or `oauth2` credentials.',
    '- `payload` — request body for `POST` / `PUT` / `PATCH` operations.',
    '- `parameters` — path parameters for operations that declare them.',
    '- `queryParams`, `pagination`, `retry`, and `hooks` for advanced control.'
  ];

  if (operations.length > 1) {
    lines.push('', '#### Available operations', '');
    for (const operation of operations) {
      lines.push(`- \`${operation.functionName}\``);
    }
  }

  return lines;
}

function renderMessagingProtocolSection({
  protocol,
  functions,
  importPath
}: {
  protocol: string;
  functions: TypeScriptChannelRenderedFunctionType[];
  importPath: string;
}): string[] {
  const label = PROTOCOL_LABELS[protocol] ?? protocol;
  const lines = [
    `### ${label}`,
    '',
    `The following channel functions handle ${label} communication:`,
    ''
  ];
  for (const channelFunction of functions) {
    lines.push(
      `- \`${channelFunction.functionName}\` — ${describeFunctionDirection(channelFunction)} \`${channelFunction.messageType}\``
    );
  }
  const primary = functions[0];
  lines.push(
    '',
    TS_FENCE,
    `import { ${primary.functionName} } from '${importPath}'`,
    CODE_FENCE
  );
  return lines;
}

function describeFunctionDirection(
  channelFunction: TypeScriptChannelRenderedFunctionType
): string {
  if (sendingFunctionTypes.includes(channelFunction.functionType)) {
    return 'sends';
  }
  if (receivingFunctionTypes.includes(channelFunction.functionType)) {
    return 'receives';
  }
  return 'handles';
}

function renderClientSection({
  client,
  channels,
  importPath
}: {
  client: TypeScriptClientRenderType;
  channels?: TypeScriptChannelRenderType;
  importPath: string;
}): string[] {
  if (!client.protocolResult.nats) {
    return [];
  }
  const lines = [
    '### Client',
    '',
    'The generated `NatsClient` wraps the channel functions with built-in connection handling:',
    '',
    TS_FENCE,
    `import { NatsClient } from '${importPath}'`,
    '',
    'const client = new NatsClient()',
    `await client.connectToHost('nats://localhost:4222')`
  ];
  const natsFunctions = channels?.renderedFunctions['nats'] ?? [];
  const primarySender = natsFunctions.find((channelFunction) =>
    sendingFunctionTypes.includes(channelFunction.functionType)
  );
  if (primarySender) {
    lines.push('', `await client.${primarySender.functionName}({ message })`);
  }
  lines.push(CODE_FENCE);
  return lines;
}

function renderPayloadsSection({
  payloads,
  importPath
}: {
  payloads: TypeScriptPayloadRenderType;
  importPath: string;
}): string[] {
  const primary = pickPrimaryPayload(payloads);
  if (!primary) {
    return [];
  }
  return [
    '### Message payloads',
    '',
    'Payload models validate, marshal, and unmarshal message data:',
    '',
    TS_FENCE,
    `import { ${primary.messageType} } from '${importPath}'`,
    '',
    `const message = new ${primary.messageType}({/* … */})`,
    'const json = message.marshal()',
    `const decoded = ${primary.messageType}.unmarshal(json)`,
    CODE_FENCE
  ];
}

function pickPrimaryPayload(
  payloads: TypeScriptPayloadRenderType
): ChannelPayload | undefined {
  const candidates = [
    ...Object.values(payloads.channelModels),
    ...Object.values(payloads.operationModels),
    ...payloads.otherModels
  ];
  return candidates.find(
    (candidate) =>
      candidate.messageModel.model instanceof ConstrainedObjectModel &&
      IDENTIFIER_REGEX.test(candidate.messageType)
  );
}

function renderTypesSection({
  types,
  importPath
}: {
  types: TypeScriptTypesRenderType;
  importPath: string;
}): string[] {
  const exportedNames = extractExportedNames(types.result);
  if (exportedNames.length === 0) {
    return [];
  }
  const shownNames = exportedNames.slice(0, 8);
  const lines = [
    '### Types',
    '',
    'General purpose types generated from the input document:',
    ''
  ];
  for (const name of shownNames) {
    lines.push(`- \`${name}\``);
  }
  lines.push(
    '',
    TS_FENCE,
    `import { ${shownNames[0]} } from '${importPath}'`,
    CODE_FENCE
  );
  return lines;
}

function extractExportedNames(content: string): string[] {
  const matches = content.matchAll(
    /export (?:type|enum|interface|class|const|function) (\w+)/g
  );
  return [...new Set([...matches].map((match) => match[1]))];
}
