export type Topics = 'test/primitives/string-plain' | 'test/primitives/string-min-length' | 'test/primitives/string-max-length' | 'test/primitives/string-pattern' | 'test/primitives/number-plain' | 'test/primitives/number-minimum' | 'test/primitives/number-maximum' | 'test/primitives/number-range' | 'test/primitives/integer-plain' | 'test/primitives/integer-range' | 'test/primitives/boolean-plain' | 'test/primitives/null-plain' | 'test/enums/single-string' | 'test/enums/multiple-string' | 'test/enums/integer' | 'test/enums/mixed' | 'test/enums/nullable' | 'test/objects/simple' | 'test/objects/required' | 'test/objects/optional' | 'test/objects/nested' | 'test/objects/deeply-nested' | 'test/objects/additional-true' | 'test/objects/additional-false' | 'test/objects/additional-schema' | 'test/objects/defaults' | 'test/arrays/string' | 'test/arrays/object' | 'test/arrays/nested' | 'test/arrays/min-items' | 'test/arrays/max-items' | 'test/arrays/unique-items' | 'test/arrays/tuple' | 'test/composition/oneof-two' | 'test/composition/oneof-three' | 'test/composition/oneof-discriminator' | 'test/composition/anyof-two' | 'test/composition/allof-two' | 'test/composition/allof-three' | 'test/formats/email' | 'test/formats/uri' | 'test/formats/uuid' | 'test/formats/date' | 'test/formats/datetime' | 'test/formats/time' | 'test/formats/hostname' | 'test/formats/ipv4' | 'test/formats/ipv6' | 'test/formats/object';
export type TopicIds = 'stringPlain' | 'stringMinLength' | 'stringMaxLength' | 'stringPattern' | 'numberPlain' | 'numberMinimum' | 'numberMaximum' | 'numberRange' | 'integerPlain' | 'integerRange' | 'booleanPlain' | 'nullPlain' | 'singleStringEnum' | 'multipleStringEnum' | 'integerEnum' | 'mixedTypeEnum' | 'nullableEnum' | 'simpleObject' | 'objectRequired' | 'objectOptional' | 'nestedObject' | 'deeplyNestedObject' | 'objectAdditionalTrue' | 'objectAdditionalFalse' | 'objectAdditionalSchema' | 'objectDefaults' | 'stringArray' | 'objectArray' | 'nestedArray' | 'arrayMinItems' | 'arrayMaxItems' | 'arrayUniqueItems' | 'tupleArray' | 'oneOfTwoTypes' | 'oneOfThreeTypes' | 'oneOfDiscriminator' | 'anyOfTwoTypes' | 'allOfTwoTypes' | 'allOfThreeTypes' | 'formatEmail' | 'formatUri' | 'formatUuid' | 'formatDate' | 'formatDateTime' | 'formatTime' | 'formatHostname' | 'formatIpv4' | 'formatIpv6' | 'objectFormats';
export function ToTopicIds(topic: Topics): TopicIds {
  switch (topic) {
    case 'test/primitives/string-plain':
    return 'stringPlain';
  case 'test/primitives/string-min-length':
    return 'stringMinLength';
  case 'test/primitives/string-max-length':
    return 'stringMaxLength';
  case 'test/primitives/string-pattern':
    return 'stringPattern';
  case 'test/primitives/number-plain':
    return 'numberPlain';
  case 'test/primitives/number-minimum':
    return 'numberMinimum';
  case 'test/primitives/number-maximum':
    return 'numberMaximum';
  case 'test/primitives/number-range':
    return 'numberRange';
  case 'test/primitives/integer-plain':
    return 'integerPlain';
  case 'test/primitives/integer-range':
    return 'integerRange';
  case 'test/primitives/boolean-plain':
    return 'booleanPlain';
  case 'test/primitives/null-plain':
    return 'nullPlain';
  case 'test/enums/single-string':
    return 'singleStringEnum';
  case 'test/enums/multiple-string':
    return 'multipleStringEnum';
  case 'test/enums/integer':
    return 'integerEnum';
  case 'test/enums/mixed':
    return 'mixedTypeEnum';
  case 'test/enums/nullable':
    return 'nullableEnum';
  case 'test/objects/simple':
    return 'simpleObject';
  case 'test/objects/required':
    return 'objectRequired';
  case 'test/objects/optional':
    return 'objectOptional';
  case 'test/objects/nested':
    return 'nestedObject';
  case 'test/objects/deeply-nested':
    return 'deeplyNestedObject';
  case 'test/objects/additional-true':
    return 'objectAdditionalTrue';
  case 'test/objects/additional-false':
    return 'objectAdditionalFalse';
  case 'test/objects/additional-schema':
    return 'objectAdditionalSchema';
  case 'test/objects/defaults':
    return 'objectDefaults';
  case 'test/arrays/string':
    return 'stringArray';
  case 'test/arrays/object':
    return 'objectArray';
  case 'test/arrays/nested':
    return 'nestedArray';
  case 'test/arrays/min-items':
    return 'arrayMinItems';
  case 'test/arrays/max-items':
    return 'arrayMaxItems';
  case 'test/arrays/unique-items':
    return 'arrayUniqueItems';
  case 'test/arrays/tuple':
    return 'tupleArray';
  case 'test/composition/oneof-two':
    return 'oneOfTwoTypes';
  case 'test/composition/oneof-three':
    return 'oneOfThreeTypes';
  case 'test/composition/oneof-discriminator':
    return 'oneOfDiscriminator';
  case 'test/composition/anyof-two':
    return 'anyOfTwoTypes';
  case 'test/composition/allof-two':
    return 'allOfTwoTypes';
  case 'test/composition/allof-three':
    return 'allOfThreeTypes';
  case 'test/formats/email':
    return 'formatEmail';
  case 'test/formats/uri':
    return 'formatUri';
  case 'test/formats/uuid':
    return 'formatUuid';
  case 'test/formats/date':
    return 'formatDate';
  case 'test/formats/datetime':
    return 'formatDateTime';
  case 'test/formats/time':
    return 'formatTime';
  case 'test/formats/hostname':
    return 'formatHostname';
  case 'test/formats/ipv4':
    return 'formatIpv4';
  case 'test/formats/ipv6':
    return 'formatIpv6';
  case 'test/formats/object':
    return 'objectFormats';
    default:
      throw new Error('Unknown topic: ' + topic);
  }
}
export function ToTopics(topicId: TopicIds): Topics {
  switch (topicId) {
    case 'stringPlain':
    return 'test/primitives/string-plain';
  case 'stringMinLength':
    return 'test/primitives/string-min-length';
  case 'stringMaxLength':
    return 'test/primitives/string-max-length';
  case 'stringPattern':
    return 'test/primitives/string-pattern';
  case 'numberPlain':
    return 'test/primitives/number-plain';
  case 'numberMinimum':
    return 'test/primitives/number-minimum';
  case 'numberMaximum':
    return 'test/primitives/number-maximum';
  case 'numberRange':
    return 'test/primitives/number-range';
  case 'integerPlain':
    return 'test/primitives/integer-plain';
  case 'integerRange':
    return 'test/primitives/integer-range';
  case 'booleanPlain':
    return 'test/primitives/boolean-plain';
  case 'nullPlain':
    return 'test/primitives/null-plain';
  case 'singleStringEnum':
    return 'test/enums/single-string';
  case 'multipleStringEnum':
    return 'test/enums/multiple-string';
  case 'integerEnum':
    return 'test/enums/integer';
  case 'mixedTypeEnum':
    return 'test/enums/mixed';
  case 'nullableEnum':
    return 'test/enums/nullable';
  case 'simpleObject':
    return 'test/objects/simple';
  case 'objectRequired':
    return 'test/objects/required';
  case 'objectOptional':
    return 'test/objects/optional';
  case 'nestedObject':
    return 'test/objects/nested';
  case 'deeplyNestedObject':
    return 'test/objects/deeply-nested';
  case 'objectAdditionalTrue':
    return 'test/objects/additional-true';
  case 'objectAdditionalFalse':
    return 'test/objects/additional-false';
  case 'objectAdditionalSchema':
    return 'test/objects/additional-schema';
  case 'objectDefaults':
    return 'test/objects/defaults';
  case 'stringArray':
    return 'test/arrays/string';
  case 'objectArray':
    return 'test/arrays/object';
  case 'nestedArray':
    return 'test/arrays/nested';
  case 'arrayMinItems':
    return 'test/arrays/min-items';
  case 'arrayMaxItems':
    return 'test/arrays/max-items';
  case 'arrayUniqueItems':
    return 'test/arrays/unique-items';
  case 'tupleArray':
    return 'test/arrays/tuple';
  case 'oneOfTwoTypes':
    return 'test/composition/oneof-two';
  case 'oneOfThreeTypes':
    return 'test/composition/oneof-three';
  case 'oneOfDiscriminator':
    return 'test/composition/oneof-discriminator';
  case 'anyOfTwoTypes':
    return 'test/composition/anyof-two';
  case 'allOfTwoTypes':
    return 'test/composition/allof-two';
  case 'allOfThreeTypes':
    return 'test/composition/allof-three';
  case 'formatEmail':
    return 'test/formats/email';
  case 'formatUri':
    return 'test/formats/uri';
  case 'formatUuid':
    return 'test/formats/uuid';
  case 'formatDate':
    return 'test/formats/date';
  case 'formatDateTime':
    return 'test/formats/datetime';
  case 'formatTime':
    return 'test/formats/time';
  case 'formatHostname':
    return 'test/formats/hostname';
  case 'formatIpv4':
    return 'test/formats/ipv4';
  case 'formatIpv6':
    return 'test/formats/ipv6';
  case 'objectFormats':
    return 'test/formats/object';
    default:
      throw new Error('Unknown topic ID: ' + topicId);
  }
}
export const TopicsMap: Record<TopicIds, Topics> = {
  'stringPlain': 'test/primitives/string-plain', 
  'stringMinLength': 'test/primitives/string-min-length', 
  'stringMaxLength': 'test/primitives/string-max-length', 
  'stringPattern': 'test/primitives/string-pattern', 
  'numberPlain': 'test/primitives/number-plain', 
  'numberMinimum': 'test/primitives/number-minimum', 
  'numberMaximum': 'test/primitives/number-maximum', 
  'numberRange': 'test/primitives/number-range', 
  'integerPlain': 'test/primitives/integer-plain', 
  'integerRange': 'test/primitives/integer-range', 
  'booleanPlain': 'test/primitives/boolean-plain', 
  'nullPlain': 'test/primitives/null-plain', 
  'singleStringEnum': 'test/enums/single-string', 
  'multipleStringEnum': 'test/enums/multiple-string', 
  'integerEnum': 'test/enums/integer', 
  'mixedTypeEnum': 'test/enums/mixed', 
  'nullableEnum': 'test/enums/nullable', 
  'simpleObject': 'test/objects/simple', 
  'objectRequired': 'test/objects/required', 
  'objectOptional': 'test/objects/optional', 
  'nestedObject': 'test/objects/nested', 
  'deeplyNestedObject': 'test/objects/deeply-nested', 
  'objectAdditionalTrue': 'test/objects/additional-true', 
  'objectAdditionalFalse': 'test/objects/additional-false', 
  'objectAdditionalSchema': 'test/objects/additional-schema', 
  'objectDefaults': 'test/objects/defaults', 
  'stringArray': 'test/arrays/string', 
  'objectArray': 'test/arrays/object', 
  'nestedArray': 'test/arrays/nested', 
  'arrayMinItems': 'test/arrays/min-items', 
  'arrayMaxItems': 'test/arrays/max-items', 
  'arrayUniqueItems': 'test/arrays/unique-items', 
  'tupleArray': 'test/arrays/tuple', 
  'oneOfTwoTypes': 'test/composition/oneof-two', 
  'oneOfThreeTypes': 'test/composition/oneof-three', 
  'oneOfDiscriminator': 'test/composition/oneof-discriminator', 
  'anyOfTwoTypes': 'test/composition/anyof-two', 
  'allOfTwoTypes': 'test/composition/allof-two', 
  'allOfThreeTypes': 'test/composition/allof-three', 
  'formatEmail': 'test/formats/email', 
  'formatUri': 'test/formats/uri', 
  'formatUuid': 'test/formats/uuid', 
  'formatDate': 'test/formats/date', 
  'formatDateTime': 'test/formats/datetime', 
  'formatTime': 'test/formats/time', 
  'formatHostname': 'test/formats/hostname', 
  'formatIpv4': 'test/formats/ipv4', 
  'formatIpv6': 'test/formats/ipv6', 
  'objectFormats': 'test/formats/object'
};
