name: Bump Homebrew formula for CLI

on:
  # Since now release depends on schedule, might be that there is a situation we cannot wait for schedule and trigger release manually
  workflow_dispatch:
  # We cannot run brew release continusly every time we release something as sometimes we release a couple of times a day and overload brew pipelines
  # schedule:
  #   - cron: "0 23 * * *"

jobs:
  bump-formula-in-homebrew:
    if: github.repository == 'the-codegen-project/cli'
    name: Bump the formula in homebrew-core repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Get version from package.json
        id: extractver
        run: echo "version=$(npm run get-version --silent)" >> $GITHUB_OUTPUT
      - uses: mislav/bump-homebrew-formula-action@v2
        with:
          # A PR will be sent to github.com/Homebrew/homebrew-core to update The Codegen Project formula:
          formula-name: the-codegen-project
          # https://github.com/mislav/bump-homebrew-formula-action/issues/58
          formula-path: Formula/a/the-codegen-project.rb
          tag-name: ${{ steps.extractver.outputs.version }}
          download-url: https://registry.npmjs.org/@the-codegen-project/cli/-/cli-${{ steps.extractver.outputs.version }}.tgz #we need to point to npm not github as there is a dist that is not on github
        env:
          COMMITTER_TOKEN: ${{ secrets.GH_TOKEN_BOT_EVE }}