name: Version bump

on: 
  release:
    types: 
      - published

jobs:
  version_bump:
    name: Generate assets and bump NodeJS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # target branch of release. More info https://docs.github.com/en/rest/reference/repos#releases
          # in case release is created from release branch then we need to checkout from given branch
          # if @semantic-release/github is used to publish, the minimum version is 7.2.0 for proper working
          ref: ${{ github.event.release.target_commitish }}
      - name: Check package-lock version
        uses: asyncapi/.github/.github/actions/get-node-version-from-package-lock@master
        id: lockversion
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.lockversion.outputs.version }}"
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Bump version in package.json
        # There is no need to substract "v" from the tag as version script handles it
        # When adding "bump:version" script in package.json, make sure no tags are added by default (--no-git-tag-version) as they are already added by release workflow
        # When adding "bump:version" script in package.json, make sure --allow-same-version is set in case someone forgot and updated package.json manually and we want to avoide this action to fail and raise confusion
        run: VERSION=${{github.event.release.tag_name}} npm run bump:version
      - name: Assets generation
        run: npm run generate:assets --if-present
      - name: Create Pull Request with updated asset files including package.json
        uses: peter-evans/create-pull-request@38e0b6e68b4c852a5500a94740f0e535e0d7ba54 # use 4.2.4 https://github.com/peter-evans/create-pull-request/releases/tag/v4.2.4
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: 'chore(release): ${{github.event.release.tag_name}}'
          committer: jonaslagoni <jonas-lt@live.dk>
          author: jonaslagoni <jonas-lt@live.dk>
          title: 'chore(release): ${{github.event.release.tag_name}}'
          body: 'Version bump in package.json for release [${{github.event.release.tag_name}}](${{github.event.release.html_url}})'
          branch: version-bump/${{github.event.release.tag_name}}